json.extract! event,
  :id,
  :title,
  :lat,
  :lng,
  :start_date_time,
  :end_date_time,
  :image_content_type,
  :image_file_name,
  :image_file_size,
  :image_updated_at,
  :description,
  :price,
  :organizer_id,
  :organizer_description
